name: Deploy Backend App to EC2

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build backend docker image
        run: docker build -t kelomi44/backend-app:${{ github.sha }} -t kelomi44/backend-app:latest ./backend
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Push backend docker image to DockerHub
        run: |
          docker push kelomi44/backend-app:${{ github.sha }}
          docker push kelomi44/backend-app:latest
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o ServerAliveInterval=30 \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/userapp
            
            # Update backend image tag
            sed -i "s|kelomi44/backend-app:.*|kelomi44/backend-app:${{ github.sha }}|" docker-compose.yml
            
            # Pull and restart backend only
            docker compose pull backend
            docker compose up -d backend
            
            # Wait for backend to be healthy
            sleep 10
            docker compose ps
            
            echo "Backend deployment completed!"
          EOF