name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-app:latest  # Fixed: Use secret instead of hardcoded

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Pull the latest backend image
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend-app:latest
          
          # Stop and remove existing backend container if running
          docker stop backend_container || true
          docker rm backend_container || true
          
          # Create or update backend container WITH LINK TO MYSQL
          docker run -d \
            --name backend \
            --restart unless-stopped \
            -p 3000:3000 \
            -e DB_HOST=mysql_container \
            -e DB_PORT=3306 \
            -e DB_USER=root \
            -e DB_PASSWORD=edoRor@44 \
            -e DB_DATABASE=crud_operations \
            --link mysql_container:mysql \  # ← CRITICAL: ADD THIS LINE
            ${{ secrets.DOCKERHUB_USERNAME }}/backend-app:latest
          
          # Clean up unused images
          docker image prune -af