name: Deploy Frontend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags:kelomi44/frontend-app:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Pull the latest frontend image
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app:latest
          
          # Stop and remove existing frontend container if running
          docker stop frontend_container || true
          docker rm frontend_container || true
          
          # Create or update frontend container
          docker run -d \
            --name frontend_container \
            --restart unless-stopped \
            -p 5000:80 \
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app:latest
          
          # Clean up unused images
          docker image prune -af