name: Deploy Frontend to EC2

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'docker-compose.yml'
      - '.github/workflows/frontend.yml'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build frontend docker image
        run: |
          docker build \
            -t kelomi44/frontend-app:${{ github.sha }} \
            -t kelomi44/frontend-app:latest \
            ./frontend
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Push frontend docker image to DockerHub
        run: |
          docker push kelomi44/frontend-app:${{ github.sha }}
          docker push kelomi44/frontend-app:latest
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      
      - name: Deploy frontend to EC2
        env:
          SSH_USER: ${{ secrets.EC2_USER }}
          SSH_HOST: ${{ secrets.EC2_HOST }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Copy docker-compose.yml to EC2
          scp -o StrictHostKeyChecking=no \
              docker-compose.yml \
              ${SSH_USER}@${SSH_HOST}:/home/userapp/
          
          # Deploy frontend
          ssh -o StrictHostKeyChecking=no \
              ${SSH_USER}@${SSH_HOST} << 'ENDSSH'
            set -e
            cd /home/userapp
            
            # Update frontend image tag in docker-compose.yml
            sed -i "s|kelomi44/frontend-app:.*|kelomi44/frontend-app:${IMAGE_TAG}|" docker-compose.yml
            
            # Pull and restart frontend only (without affecting MySQL or backend)
            docker compose pull frontend
            docker compose up -d --no-deps frontend
            
            # Verify deployment
            sleep 5
            docker compose ps frontend
            echo "Frontend deployment completed!"
          ENDSSH